# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drive < Formula
  desc "A tool for exploring layers in a docker image"
  homepage "https://github.com/khulnasoft/drive/"
  version "0.0.0-SNAPSHOT-ee4f0c1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft/drive/releases/download/v0.0.0/drive_0.0.0-SNAPSHOT-ee4f0c1_darwin_amd64.tar.gz"
      sha256 "7a652cc9bc791effe3b9c29f20dd5dc61c1dc4cd664aedfe902ccda48d0c0538"

      def install
        bin.install "drive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khulnasoft/drive/releases/download/v0.0.0/drive_0.0.0-SNAPSHOT-ee4f0c1_darwin_arm64.tar.gz"
      sha256 "8885ede247dde2abb3fa61b616413e9c7a4dd6ec3460263ccdbb904e70bea94c"

      def install
        bin.install "drive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khulnasoft/drive/releases/download/v0.0.0/drive_0.0.0-SNAPSHOT-ee4f0c1_linux_arm64.tar.gz"
      sha256 "7088d4cb5f9fb15da5f0ed9cf58296cfdd8c84eaef33336bc73f31aee7023e67"

      def install
        bin.install "drive"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft/drive/releases/download/v0.0.0/drive_0.0.0-SNAPSHOT-ee4f0c1_linux_amd64.tar.gz"
      sha256 "9777b7f58ad8240d60e07bc9fd0cd97c0b5c868f91f14d3a67309cf4b339f67a"

      def install
        bin.install "drive"
      end
    end
  end
end
