# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCipherguardCli < Formula
  desc "A CLI tool to interact with Cipherguard, a Open source Password Manager for Teams"
  homepage "https://github.com/khulnasoft/go-cipherguard-cli"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cipherguard/go-cipherguard-cli/releases/download/v0.3.1/go-cipherguard-cli_0.3.1_darwin_amd64.tar.gz"
      sha256 "42f777641655f67300991fcd3e9961fb60febeb2e86dade061b243b3f3441ad4"

      def install
        bin.install "cipherguard"
        bash_completion.install "completion/bash" => "cipherguard"
        zsh_completion.install "completion/zsh" => "_cipherguard"
        fish_completion.install "completion/fish" => "cipherguard.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cipherguard/go-cipherguard-cli/releases/download/v0.3.1/go-cipherguard-cli_0.3.1_darwin_arm64.tar.gz"
      sha256 "136ded82b3d02c63b2be11bd889a13e8e19ba738b8263cfd8a7a12f06a85e04c"

      def install
        bin.install "cipherguard"
        bash_completion.install "completion/bash" => "cipherguard"
        zsh_completion.install "completion/zsh" => "_cipherguard"
        fish_completion.install "completion/fish" => "cipherguard.fish"
        man1.install Dir["man/*"]
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cipherguard/go-cipherguard-cli/releases/download/v0.3.1/go-cipherguard-cli_0.3.1_linux_amd64.tar.gz"
        sha256 "90c1027e7ebeb04ac9fb43a314ba8c0e382e2e391e31f1b9d32fc962ce9503eb"

        def install
          bin.install "cipherguard"
          bash_completion.install "completion/bash" => "cipherguard"
          zsh_completion.install "completion/zsh" => "_cipherguard"
          fish_completion.install "completion/fish" => "cipherguard.fish"
          man1.install Dir["man/*"]
          # ...
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cipherguard/go-cipherguard-cli/releases/download/v0.3.1/go-cipherguard-cli_0.3.1_linux_arm64.tar.gz"
        sha256 "ee32a9b5f44f35e70a8a48cb7872aa4d670350fc28d612fa8ca32adf6457b3b6"

        def install
          bin.install "cipherguard"
          bash_completion.install "completion/bash" => "cipherguard"
          zsh_completion.install "completion/zsh" => "_cipherguard"
          fish_completion.install "completion/fish" => "cipherguard.fish"
          man1.install Dir["man/*"]
          # ...
        end
      end
    end
  end
end
